Mention feature is added
muhammetaliakbay/slack-poll pull request #2
Opened 2021-11-30 14:33 UTC by VTAkbay

2021-11-30 14:40 UTC, muhammetaliakbay requested changes
It would be good if you could simplfy the code

2021-11-30 14:40 UTC, muhammetaliakbay commented on src/bot/create.ts
> +                    text: mentionOwner + " has started a new poll!",
This would be more readable:
```ts
text: `<@${userId}> has started a new poll!`
```

2021-11-30 15:12 UTC, muhammetaliakbay approved these changes
👍 LGTM

2021-11-30 15:28 UTC, merged

2021-12-10 22:22 UTC, VTAkbay commented
Bots not adding to database on vote_right.